# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Shristi Shrestha
tagline:          'Shristi Shrestha: A Personal Profile Page'
description:      'Graduate Student Computer Science Louisiana State University Baton Rouge, LA'
url:              https://github.com/ShristiShrestha
# https://shristishrestha.github.io
baseurl:          

author:
  name:           'Shristi'
  url:            https://twitter.com/Shrististha7

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ShristiShrestha
  hyde:           https://github.com/poole/hyde

research:
  rate_features:    https://ratefeatureappstore-e2366.web.app/

plugins:
  - jekyll-paginate

include:
  - public
