# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: false
# defaults:
# - scope:
#   path: ""
#   type: "pages"
# values:
#   permalink: "/:title"

# Setup
title:            CHISE
tagline:          'Computer Human Interactions and Software Engineering'
description:      'A Bunch of Geeks Solving Problems'
url:              

baseurl:          

include:
  - public

paginate:         5

# Custom vars
version:          2.1.0

plugins:
  - jekyll-paginate
