# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            CHISE
tagline:          'Computer Human Interactions and Software Engineering'
description:      'Bunch of Geeks Identifying Problems and Inventing Solutions'
url:              
# https://shristishrestha.github.io
baseurl:          

author:
  name:           'Shristi'
  url:            https://twitter.com/Shrististha7

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ShristiShrestha
  hyde:           https://github.com/poole/hyde

plugins:
  - jekyll-paginate
